# This is a basic workflow to help you get started with Actions

name: JHusky 2.0

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
        
  # Run jobs      
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Runs a fresh install of JHusky each time the action is run
        run: |
          mvn jhusky:install -Ddirectory=.husky
          mvn jhusky:add -DhookPath=.husky/pre-commit -Dcommand="mvn clean test"
          git add .husky/pre-commit
          echo JHusky successfully installed
